"""Generate Phase-1 training data for the VC33 game (mouse-click only).

VC33 is a **tilt-and-pour liquid puzzle**. Each level is a network of connected containers
under a fixed "gravity"/tilt direction (the level's ``TiD`` datum, e.g. ``[2, 0]`` = liquid
drifts right by 2px per pour, ``[0, -2]`` = up). Coloured liquid columns fill the containers.
Floating on the surface of each liquid is a **head** (an ``HQB`` sprite, e.g. ``ChX`` / ``cni``
/ ``Ubu``), whose bottom-row colour is the liquid's identity. On the walls sit **identifiers**
(``fZK`` sprites, e.g. ``EtZ`` / ``UIT``), each drawn in one liquid colour. The level is solved
(``gug`` returns True) when **every head sits at the same along-tilt coordinate as an identifier
of its own colour, connected to it through the liquid** -- i.e. each colour of liquid has been
routed so its surface lines up under the matching marker.

You act only by **clicking** (``GameAction.ACTION6``). Two things are clickable:

  * **Pour squares** (``ZGd`` sprites ``xQZ`` / ``MPi``, layer 1, pixel-perfect). Each square is
    bound at level load (``on_set_level`` builds ``self.dzy``) to an ordered pair of container
    columns; clicking it (``ccl`` -> ``gel``) transfers one tilt-step of liquid from the source
    column to the destination, which slides that column's head by the tilt vector. Clicking the
    two squares that share a pair pushes a head back and forth along the container.
  * **Pillars** (``zHk`` sprites ``dBq`` / ``WfE``) -- but only when ``krt`` holds (the pillar is
    wedged between two walls). Clicking a wedged pillar (``teu``) plays a multi-frame animation
    (``ysn`` / ``diu``) that collapses the pillar and the liquid around it, opening a new flow
    path. A clicked pillar that is not wedged does nothing.

Every click costs one unit of the per-level action budget (``RoA``, shown as the top HUD bar
``ehv``); run it to zero without solving and you lose (``lose``). A pillar's whole animation is
still a single click -- the budget is decremented once, when the click lands.

Migration notes (this file is now a thin ``BaseSolver`` subclass)
----------------------------------------------------------------
The record/replay loop, the episode schema, the WIN-filter CLI and the optional exploration
prefix all live in ``BaseSolver``. This file supplies only the VC33 expert:

1. **The engine IS the model -- search drives the real game.** The pour/collapse dynamics are a
   pile of geometric special cases (``gel`` trims and regrows container pixel columns, ``teu``
   scripts a per-pixel collapse animation, ``mud`` computes flow limits from boundary sprites),
   and re-deriving them from the obfuscated source would be guesswork. So each search node holds
   a real ``Vc33`` instance and successors are generated by actually clicking, which makes every
   plan correct by construction. The search is **greedy best-first over clicks**: the successors
   of a state are "click each pour square, and each currently-wedged pillar".
   ``_fast_copy`` (the sc25 trick) shares the six untouched levels so a single-level copy is ~7x
   cheaper. Because the search snapshots whole levels by ``deepcopy``, ``supports_recovery`` stays
   ``False`` (pure optimal replay; no exploration prefix): the expert plans from a level's initial
   state, not from an arbitrary perturbed one.

2. **Plans are seed-independent -- solved ONCE per level, replayed for every seed.** ``Vc33``'s
   seed only re-rolls the *palette*; the geometry (container layout, square bindings, pillar
   positions, tilt) is identical across seeds, and the remap is colour-*consistent* so "head
   colour == identifier colour" is preserved. So a grid-click sequence that solves level *k* on
   one seed solves it on every seed. ``solve_from`` caches the grid-click plan per level index in
   memory (and warm-loads ``data/vc33_plans.json`` when present); every later seed replays it for
   free, converting the grid cells to that seed/level's live display coordinates.

3. **Episodes are recorded at the NATURAL display rotation.** ``Vc33`` is an ``AugmentedGame``,
   so every level is displayed at ``random_rotation_k(seed, level)``. Rotation is a pure DISPLAY
   transform -- grid cells, sprite positions and plans are untouched -- so planning stays
   rotation-invariant; only the click needs converting. ``_display_coord`` applies the inverse
   (``remap_click(..., -k)``, the identity at k=0) so the recorded action is the SCREEN coordinate
   actually clicked. Levels are advanced in place via ``_really_set_next_level`` (see ``set_level``)
   so each level keeps the natural rotation the engine just drew for it.

Action schema (same corpus convention as sc25 / ka59 / m0r0):

    RESET :  {"type": "simple", "index": 0}      (leading action for obs[0])
    click :  {"type": "mouse",  "index": 6, "data": {"x": x, "y": y}}

Usage (run from the repo root, with the ARC-AGI-3 conda python):
    python solvers/generate_vc33_training.py --episodes 500
"""

from __future__ import annotations

import copy
import heapq
import itertools
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np  # noqa: E402
from arcengine import ActionInput, GameAction, GameState  # noqa: E402
from games.vc33.vc33 import Vc33  # noqa: E402
from solvers.base_solver import BaseSolver  # noqa: E402
from utils.explore import Action, CLICK_ACTION  # noqa: E402
from utils.rotation import remap_click  # noqa: E402

_STEP_GUARD = 30000
_DEFAULT_PLAN_CACHE = Path("data/vc33_plans.json")


# ── engine helpers ─────────────────────────────────────────────────────────────
def _fast_copy(game):
    """Deep-copy the game, SHARING the levels the search cannot touch (sc25's trick).

    A plain deepcopy duplicates all 7 live levels; a single-level search mutates exactly one.
    Pre-seeding the memo with the other six (and ``_clean_levels``, never touched here) makes
    the copy several times cheaper. Safe because the search never calls ``set_level``."""
    memo = {id(game._clean_levels): game._clean_levels}
    for i, level in enumerate(game._levels):
        if i != game.level_index:
            memo[id(level)] = level
    return copy.deepcopy(game, memo)


def _display_coord(game, gx: int, gy: int) -> tuple[int, int]:
    """Display (screen) coordinate whose ``display_to_grid`` is grid cell (gx, gy).

    The camera resizes to each level's grid, so a 32-grid renders at 2x and a 64-grid at 1x.
    That scaled centre is a GAME-space pixel, inverse-rotated into the screen space a player
    clicks in (``remap_click(..., -k)``, identity at k=0)."""
    scale, ox, oy = game.camera._calculate_scale_and_offset()
    gpx = int(gx * scale + ox + scale // 2)
    gpy = int(gy * scale + oy + scale // 2)
    return (gpx, gpy)


def _drive_search(game, dx: int, dy: int):
    """Send one click to (dx, dy) and run it to completion (search-only; no render).
    Returns (solved, dead)."""
    game._full_reset = False
    game._set_action(ActionInput(id=GameAction.ACTION6, data={"x": dx, "y": dy}))
    guard = 0
    while not game.is_action_complete():
        if guard > _STEP_GUARD or game._next_level:
            break
        game.step()
        guard += 1
    solved = bool(game._next_level) or game._state == GameState.WIN
    return solved, game._state == GameState.GAME_OVER


def _click_cells(game) -> list[tuple[int, int]]:
    """Grid cells worth clicking in this state: every pour square, plus every currently-wedged
    pillar (an un-wedged pillar click is a no-op, so it is never a useful successor)."""
    level = game.current_level
    cells = [(s.x + s.width // 2, s.y + s.height // 2) for s in level.get_sprites_by_tag("ZGd")]
    for s in level.get_sprites_by_tag("zHk"):
        if game.krt(s):
            cells.append((s.x + s.width // 2, s.y + s.height // 2))
    return cells


def _state_key(game):
    """Full, exact state: the position and pixel content of every sprite. Sound for dedup, so a
    search using it is complete."""
    return tuple(sorted(
        (s.name, s.x, s.y, s.pixels.shape, hash(s.pixels.tobytes()))
        for s in game.current_level.get_sprites()
    ))


def _coarse_key(game):
    """A lossy state key: only head positions, pillar wedge-states, and goal-box count. Collapses
    the pillar-shuffling plateau that stalls the full-key search on the multi-head level (L7); used
    only as a FALLBACK. Any plan it returns is still engine-verified."""
    level = game.current_level
    heads = tuple(sorted((s.name, s.x, s.y) for s in level.get_sprites_by_tag("HQB")))
    pillars = tuple(sorted((s.name, s.x, s.y, game.krt(s))
                           for s in level.get_sprites_by_tag("zHk")))
    boxes = len(level.get_sprites_by_tag("rlV"))
    return (heads, pillars, boxes)


# ── search ─────────────────────────────────────────────────────────────────────
def _heuristic(game) -> float:
    """Total along-tilt distance from each head to the nearest identifier of its own colour,
    divided by the tilt magnitude. A pour moves a head by one tilt vector, so this lower-bounds
    the remaining pours and steers the search at lining each head up under its marker."""
    oro = game.oro
    mag = abs(oro[0]) if oro[0] else abs(oro[1])
    along = (lambda s: s.x) if oro[0] else (lambda s: s.y)
    level = game.current_level
    heads = level.get_sprites_by_tag("HQB")
    identifiers = level.get_sprites_by_tag("fZK")
    total = 0
    for head in heads:
        colour = head.pixels[-1, -1]
        dists = [abs(along(head) - along(i)) for i in identifiers if colour in i.pixels]
        if dists:
            total += min(dists)
    return total / max(1, mag)


def _greedy_search(game, keyfn, time_limit: float, *, verbose: bool = False):
    """Greedy best-first over clicks on the REAL engine, deduping by ``keyfn``.

    Returns (plan, status) with status in {"solved", "exhausted", "timeout"}. ``plan`` is the
    list of grid cells to click, in order (None unless status == "solved"). ``game`` is never
    mutated -- every successor is a ``_fast_copy``."""
    start = _fast_copy(game)
    budget = start.vrr.olv
    counter = itertools.count()
    pq = [(_heuristic(start), 0, next(counter), start, [])]
    best = {keyfn(start): 0}
    expanded = 0
    t0 = time.time()
    while pq:
        _, cost, _, node, path = heapq.heappop(pq)
        expanded += 1
        if time.time() - t0 > time_limit:
            if verbose:
                print(f"    TIMEOUT after {expanded} nodes", flush=True)
            return None, "timeout"
        for (gx, gy) in _click_cells(node):
            nxt = _fast_copy(node)
            dx, dy = _display_coord(nxt, gx, gy)
            solved, dead = _drive_search(nxt, dx, dy)
            if dead:
                continue
            if solved:
                if verbose:
                    print(f"    solved: {cost + 1} clicks/{budget} budget, {expanded} nodes, "
                          f"{time.time() - t0:.1f}s", flush=True)
                return path + [(gx, gy)], "solved"
            if nxt.vrr.olv <= 0:
                continue
            new_cost = cost + 1
            key = keyfn(nxt)
            if key in best and best[key] <= new_cost:
                continue
            best[key] = new_cost
            heapq.heappush(pq, (_heuristic(nxt), new_cost, next(counter), nxt, path + [(gx, gy)]))
    return None, "exhausted"


def solve_level(game, *, time_limit_full: float = 200.0, time_limit_coarse: float = 900.0,
                verbose: bool = False):
    """Solve one level, returning (plan, proved). Two tiers, both driving the real engine so every
    returned plan is correct by construction: full-key greedy (complete) then a coarse-key greedy
    fallback only when tier 1 times out. ``proved`` is True when the answer is final."""
    plan, status = _greedy_search(game, _state_key, time_limit_full, verbose=verbose)
    if status == "solved":
        return plan, True
    if status == "exhausted":
        return None, True
    if verbose:
        print("    full-key timed out -> coarse-key fallback ...", flush=True)
    plan, status = _greedy_search(game, _coarse_key, time_limit_coarse, verbose=verbose)
    if status == "solved":
        return plan, True
    return None, False


# ── solver ─────────────────────────────────────────────────────────────────────
class Vc33Solver(BaseSolver):
    game_id = "vc33"
    # RESET-recovery: the greedy search plans from a level's INITIAL state (its grid-click
    # plan is cached per level index), not from an arbitrary perturbed one, so exploration
    # explores the prefix, RESETs back to the initial state (via ``reset_level``), then
    # replays the cached plan -- the "reset" paradigm.
    supports_recovery = True
    recovery_mode = "reset"
    step_guard = _STEP_GUARD

    def __init__(self, *, plan_cache: Path | None = _DEFAULT_PLAN_CACHE, **kwargs):
        super().__init__(**kwargs)
        # Grid-click plans keyed by level index; seed-independent, so one solve serves every seed.
        self._plan_cache: dict[int, list[tuple[int, int]]] = {}
        if plan_cache and Path(plan_cache).exists():
            self._plan_cache = {int(k): [tuple(c) for c in v]
                                for k, v in json.loads(Path(plan_cache).read_text()).items()}

    def make_game(self, seed: int):
        return Vc33(seed=seed)  # natural per-level rotation (AugmentedGame)

    def available_actions(self, game) -> list[int]:
        return [CLICK_ACTION]

    def set_level(self, game, level_idx: int) -> None:
        """Advance in place, honouring the engine's queued next-level (which keeps the natural
        rotation ``on_set_level`` just drew) rather than jumping with a fresh ``set_level``."""
        if game.level_index == level_idx:
            return
        if game._next_level:
            game._really_set_next_level()
        if game.level_index != level_idx:
            game.set_level(level_idx)

    def reset_level(self, game, level_idx: int, seed: int) -> None:
        """Restore ``level_idx`` to its INITIAL state (the frame ``record_level`` captured
        as ``observations[0]``). ``set_level`` ADVANCES the single ``Vc33`` instance in
        place, so the base ``reset_level`` cannot restore it. Instead rebuild the level the
        way it was first recorded: a fresh ``Vc33(seed)`` advanced to ``level_idx`` through
        the engine's own in-place ``_really_set_next_level`` (running each ``on_set_level``
        once, so the container layout, square bindings and natural rotation are reproduced),
        then transplant that fresh state into ``game``."""
        fresh = self.make_game(seed)
        for _ in range(level_idx):
            fresh._really_set_next_level()
        game.__dict__.update(fresh.__dict__)

    def solve_from(self, game, level_idx: int, seed: int):
        """Grid-click plan for the current level, converted to this seed/level's live display
        coordinates. The grid plan is cached (seed-independent); a cache miss solves on the live
        instance (``solve_level`` never mutates it -- it searches ``_fast_copy`` snapshots)."""
        if level_idx not in self._plan_cache:
            plan, proved = solve_level(game)
            if proved:
                self._plan_cache[level_idx] = plan or []
            elif plan is None:
                return []
            else:
                self._plan_cache[level_idx] = plan
        plan = self._plan_cache.get(level_idx) or []
        if not plan:
            return []
        actions = []
        for gx, gy in plan:
            dx, dy = _display_coord(game, gx, gy)
            actions.append(Action(CLICK_ACTION, (dy, dx)))  # click_rc = (row=y, col=x)
        return actions


if __name__ == "__main__":
    sys.exit(Vc33Solver.main())
