"""Generate Phase-1 training data for the TU93 game (keyboard-only).

TU93 is a **turn-based pursuit maze**. The board (tag ``vhlesexlqd``) is not a pixel maze but a
*graph*: nodes sit on a 6px lattice and are drawn as 3x3 blocks of colour 0, and the 3x3 block
between two adjacent nodes is colour 2 when an edge joins them and -1 when it does not. The
avatar (``mcrwthchct``) walks that graph one node per action and must stand on the exit
(``xtivqldqva``); guards patrol it. Colours 0 and 2 are excluded from the palette draw, so the
maze always reads the same no matter what the seed does to everything else.

Mechanics (obfuscated ``games/tu93/tu93.py``; all of the below is verified against the engine by
the original ``--verify`` harness, not just read off the source):

  * **One action = one node.** ACTION1/2/3/4 = up/down/left/right. ``step`` is a 3-phase state
    machine (``iuubfszcoi``): phase 0 accepts the press, phases 1-2 animate the 6px slide 1px at
    a time, so a legal move spans 8 engine ticks and an action is one full node-to-node move.
  * **An illegal press costs a step and freezes the world.** Phase 0 decrements the counter
    *before* testing for an edge, and with no edge it never reaches phase 1, so the enemies do
    not move. There is no wait action -- the world only advances when the avatar actually moves.
  * **The avatar moves first, then everything else.** Walking onto an enemy destroys it; an
    enemy that walks onto the avatar destroys the avatar. Head-on swaps are won by the avatar.
  * **Guards** (``vllvfeggte``) are static lethal nodes: the one node they face. Own node is safe.
  * **Patrols** (``zzuxulcort``) move one node every action, wall-agnostic, flipping at a dead end.
  * **Shadows** (``natiyqayts``) replay the avatar's moves two behind, once triggered -- reversing
    while shadowed is death.
  * **Budget.** ``StepCounter`` actions per level (20-60); the win test precedes the budget check.

Four TU93-specific decisions (unchanged by the BaseSolver migration)
--------------------------------------------------------------------
1. **The engine IS the model -- A* drives the real game.** Search nodes hold real ``Tu93``
   instances and successors are generated by actually driving the engine, so every plan is
   correct by construction. ``_fast_copy`` (the sc25 trick) shares the untouched levels.
2. **One plan per level, not per seed.** Geometry is seed-invariant (a seed only picks a palette
   and a frame rotation), so the optimal plan is a function of the level index alone: 9 plans,
   solved once, cached in ``data/tu93_plans.json`` and replayed by every later seed for free.
3. **Rotation stays LIVE; the plan is stored in game space.** The plan is solved in game space
   (the search pins its copy to k=0) and each seed replays it at its own live rotation via
   ``inverse_remap_action_full`` -- so a seed varies the frames *and* the recorded action indices.
4. **Illegal moves are never planned, for free.** An illegal press leaves the world untouched, so
   its successor's state key equals its parent's, which A* has already closed.

Episode model: **single-game-multi-level, all-or-nothing.** One ``Tu93(seed)`` instance plays
every level in sequence; a single unsolved level fails the whole episode. This is the BaseSolver
default (``solve_episode`` iterates the levels on one instance, advancing via ``set_level`` --
which is a pure function of ``(seed, level)`` here, so it is byte-identical to the engine's own
in-place level advance).

Action schema (same corpus convention as ka59 / m0r0 / dc22):

    RESET :  {"type": "simple", "index": 0}      (leading action for obs[0])
    move  :  {"type": "simple", "index": 1|2|3|4}

Usage (run from the repo root, with the ARC-AGI-3 conda python):

    python solvers/generate_tu93_training.py --episodes 1600 --out data/training_multi_level/tu93
"""

from __future__ import annotations

import copy
import heapq
import json
import sys
import time
from collections import deque
from pathlib import Path

import numpy as np

# Repo root (parent of solvers/) -- that's where the games/ package lives.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from arcengine import ActionInput, GameAction, GameState  # noqa: E402
from games.tu93.tu93 import Tu93  # noqa: E402
from utils.rotation import inverse_remap_action_full  # noqa: E402
from solvers.base_solver import BaseSolver  # noqa: E402
from utils.explore import Action  # noqa: E402

_DEFAULT_PLAN_CACHE = Path("data/tu93_plans.json")
_STEP_GUARD = 3000

# Sprite tags (obfuscated names kept verbatim so they can be grepped in the game source).
_TAG_BOARD = "vhlesexlqd"    # the graph the avatar walks: nodes = colour 0, edges = colour 2
_TAG_PLAYER = "albwnmiahg"
_TAG_EXIT = "xboyuzuyxv"
_TAG_GUARD = "vllvfeggte"    # stands still; charges one node when faced from one node away
_TAG_PATROL = "zzuxulcort"   # moves every action, wall-agnostic, flips at a dead end
_TAG_SHADOW = "natiyqayts"   # replays the avatar's moves two behind, once triggered
_ENEMY_TAGS = (_TAG_GUARD, _TAG_PATROL, _TAG_SHADOW)

_CELL = 3                    # bsfndluqyd: one board block
_NODE = 2 * _CELL            # twsfmzbqkg: node pitch, and the distance one action covers

_ACTIONS = (1, 2, 3, 4)
_ACTION_ROT = {1: 0, 2: 180, 3: 270, 4: 90}
_ROT_DELTA = {0: (0, -1), 180: (0, 1), 270: (-1, 0), 90: (1, 0)}


# ── engine helpers ─────────────────────────────────────────────────────────────
def _game_action(index: int) -> GameAction:
    """``GameAction`` member for an action index (reverse lookup by ``.value`` is broken)."""
    return getattr(GameAction, f"ACTION{index}")


def _fast_copy(game):
    """Deep-copy the game, SHARING everything the search cannot touch (the sc25 trick)."""
    memo = {id(game._clean_levels): game._clean_levels}
    for i, level in enumerate(game._levels):
        if i != game.level_index:
            memo[id(level)] = level
    return copy.deepcopy(game, memo)


def _drive_engine(game, index: int, *, render: bool = False):
    """Run one *screen* action to completion. Returns (frame_or_None, solved, dead)."""
    game._full_reset = False
    game._set_action(ActionInput(id=_game_action(index)))
    guard = 0
    while not game.is_action_complete():
        if guard > _STEP_GUARD or game._next_level:
            break
        game.step()
        guard += 1
    frame = None
    if render:
        frame = np.asarray(game.camera.render(game.current_level.get_sprites()))
    solved = bool(game._next_level) or game._state == GameState.WIN
    return frame, solved, game._state == GameState.GAME_OVER


def _board(game):
    return game.current_level.get_sprites_by_tag(_TAG_BOARD)[0]


def _node_of(sprite, board) -> tuple[int, int]:
    """Sprite position as node coordinates (nx, ny). Every sprite sits on the lattice."""
    return ((sprite.x - board.x) // _NODE, (sprite.y - board.y) // _NODE)


def _state_key(game):
    """Everything that can affect the future, and nothing else."""
    lvl = game.current_level
    board = _board(game)
    players = tuple(sorted(_node_of(s, board) for s in lvl.get_sprites_by_tag(_TAG_PLAYER)))
    ents = []
    for tag in _ENEMY_TAGS:
        for s in lvl.get_sprites_by_tag(tag):
            nx, ny = _node_of(s, board)
            ents.append((tag, nx, ny, s.rotation,
                         bool(s.pixels[0, 1] == game._fltjxhzdlv),
                         tuple(game.sdiguidlbg.get(s, ()))))
    return (players, tuple(sorted(ents)))


# ── the maze graph (heuristic only) ──────────────────────────────────────────────
def _has_edge(board, nx: int, ny: int, rot: int) -> bool:
    px = board.pixels
    h, w = px.shape
    dx, dy = nx * _NODE, ny * _NODE
    ddx, ddy = _ROT_DELTA[rot]
    i, j = dy + ddy * _CELL, dx + ddx * _CELL
    return 0 <= i < h and 0 <= j < w and bool(px[i, j] == 2)


def _adjacency(game) -> dict:
    board = _board(game)
    h, w = board.pixels.shape
    adj = {}
    for ny in range((h + _NODE - 1) // _NODE):
        for nx in range((w + _NODE - 1) // _NODE):
            moves = {}
            for a in _ACTIONS:
                rot = _ACTION_ROT[a]
                if _has_edge(board, nx, ny, rot):
                    ddx, ddy = _ROT_DELTA[rot]
                    moves[a] = (nx + ddx, ny + ddy)
            adj[(nx, ny)] = moves
    return adj


def _distances(game) -> dict:
    board = _board(game)
    adj = _adjacency(game)
    exits = [_node_of(s, board) for s in game.current_level.get_sprites_by_tag(_TAG_EXIT)]
    dist = {e: 0 for e in exits if e in adj}
    q = deque(dist)
    while q:
        cur = q.popleft()
        for nb in adj[cur].values():
            if nb in adj and nb not in dist:
                dist[nb] = dist[cur] + 1
                q.append(nb)
    return dist


# ── the search ─────────────────────────────────────────────────────────────────
def solve_level(game, *, time_limit: float = 900.0, verbose: bool = False):
    """A* over real engine states. Returns a game-space plan (list of action indices) or None."""
    budget = game.tsoqrmroqn.current_steps
    dist = _distances(game)
    far = len(dist) + budget + 1  # unreachable node: bigger than any real remaining cost

    def h(g):
        ps = g.current_level.get_sprites_by_tag(_TAG_PLAYER)
        if not ps:
            return far
        return max((dist.get(_node_of(p, _board(g)), far) for p in ps), default=far)

    start = _fast_copy(game)
    # Pin the search to k=0 so the plan comes out in GAME space. `step` inverse-rotates every
    # press through the live `_rotation_k`, so searching on an unpinned copy would silently yield
    # a plan in the *solving seed's* screen space. Pinning the copy leaves the caller's live
    # rotation untouched.
    start._rotation_k = 0
    t0 = time.time()
    counter = 0
    open_heap = [(h(start), 0, counter, start, [])]
    seen = {_state_key(start)}
    expanded = 0

    while open_heap:
        f, g_cost, _, node, plan = heapq.heappop(open_heap)
        expanded += 1
        if expanded % 4000 == 0 and time.time() - t0 > time_limit:
            if verbose:
                print(f"      timeout after {expanded} nodes ({time.time() - t0:.0f}s)")
            return None
        if g_cost >= budget:
            continue  # every successor would be over budget
        for a in _ACTIONS:
            child = _fast_copy(node)
            _, solved, dead = _drive_engine(child, a)
            if dead:
                continue
            if solved:
                if verbose:
                    print(f"      solved: {g_cost + 1} actions (budget {budget}), "
                          f"{expanded} nodes, {time.time() - t0:.1f}s")
                return plan + [a]
            key = _state_key(child)
            if key in seen:
                continue  # includes every illegal press: the world froze, so the key is ours
            seen.add(key)
            hc = h(child)
            if hc >= far or g_cost + 1 + hc > budget:
                continue  # cannot reach the exit inside the remaining budget
            counter += 1
            heapq.heappush(open_heap, (g_cost + 1 + hc, g_cost + 1, counter, child, plan + [a]))
    if verbose:
        print(f"      exhausted after {expanded} nodes ({time.time() - t0:.1f}s)")
    return None


# ── the solver ───────────────────────────────────────────────────────────────────
class Tu93Solver(BaseSolver):
    """Turn-based pursuit maze on a node graph. One optimal plan per level (geometry is
    seed-invariant), solved once by engine-blackbox A*, cached to ``data/tu93_plans.json``, and
    replayed by every seed at its own LIVE display rotation.

    ``supports_recovery`` is True in the REPLAN paradigm: ``solve_from`` runs the engine-A*
    ``solve_level`` on the LIVE game (current player/guard nodes + remaining budget) each call,
    so it re-plans from any perturbed-but-solvable state -- the raw search is fast (<~0.4s/level).
    An off-plan detour onto a lethal guard node (GAME_OVER) or a burst that strands the avatar is
    handled by the burst-undo rollback, with RESET as the last resort.
    """

    game_id = "tu93"
    step_guard = _STEP_GUARD
    supports_recovery = True
    recovery_mode = "replan"

    def __init__(self, *args, plans_path: Path | None = None, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self._plans_path = Path(plans_path) if plans_path else _DEFAULT_PLAN_CACHE
        self._plans: dict[str, list[int]] = {}
        if self._plans_path.exists():
            with self._plans_path.open() as f:
                self._plans = json.load(f)

    def make_game(self, seed: int):
        return Tu93(seed=seed)

    def available_actions(self, game) -> list[int]:
        return [1, 2, 3, 4]

    def set_level(self, game, level_idx: int) -> None:
        """Advance to ``level_idx`` on the single episode instance.

        A level win leaves ``_next_level`` pending (``drive`` breaks on that flag rather than
        completing the transition, to capture the clean solved frame). Consume it with the engine's
        own in-place advance -- the original's mechanism -- so the next level starts clean and the
        stale flag can't make its first drive report a spurious solve. Only the very first level
        (nothing pending) uses ``set_level`` directly.
        """
        if getattr(game, "_next_level", False):
            game._really_set_next_level()
        else:
            game.set_level(level_idx)

    def reset_level(self, game, level_idx: int, seed: int) -> None:
        """Restore ``level_idx`` to its INITIAL state (the frame ``record_level`` captured
        as ``observations[0]``). ``set_level`` ADVANCES the single ``Tu93`` instance in
        place, so the base ``reset_level`` cannot restore it. Instead rebuild the level the
        way it was first recorded: a fresh ``Tu93(seed)`` advanced to ``level_idx`` through
        the engine's own in-place ``_really_set_next_level`` (running each ``on_set_level``
        once, so the seed-invariant graph + enemy layout is reproduced), then transplant that
        fresh state into ``game``."""
        fresh = self.make_game(seed)
        for _ in range(level_idx):
            fresh._really_set_next_level()
        game.__dict__.update(fresh.__dict__)

    # ── plan cache (keyed by level index -- the only thing a plan depends on) ────────
    def _cached_plan(self, game) -> list[int] | None:
        """The game-space plan for ``game``'s current level, solving + caching on a miss."""
        key = str(game.level_index)
        if key not in self._plans:
            plan = solve_level(game)
            if plan is None:
                return None
            self._plans[key] = plan
            self._save_plans()
        return self._plans[key]

    def _save_plans(self) -> None:
        self._plans_path.parent.mkdir(parents=True, exist_ok=True)
        with self._plans_path.open("w") as f:
            json.dump(self._plans, f, indent=1, sort_keys=True)

    def solve_from(self, game, level_idx: int, seed: int):
        """Return the SCREEN-space plan for ``game``'s current LIVE state.

        Re-solve the live game each call (``solve_level`` is an engine-A* over the current
        player/guard nodes + remaining budget; it pins its search copy to k=0 so the plan comes
        out in GAME space). This is what makes recovery replan-capable -- replaying a level-keyed
        cached plan would be valid only from the initial state. Each game-space action is then
        converted to the screen press a player looking at THIS seed's rotated frame would make
        (the engine undoes it via ``remap_action``). Empty list (no plan within budget) fails.
        """
        plan = solve_level(game)
        if plan is None:
            return []
        k = game._rotation_k
        return [Action(int(_game_action(a).value)) for a in plan]

    # NO `drive` override: the base one is this loop plus a render after EVERY
    # engine step, so it keeps the whole slide animation instead of only its
    # settled frame. That matters because `solver.py` feeds the policy the live
    # `FrameData.frame` list -- tu93 slides over 8 frames, so an override that
    # recorded 1 frame per action trained a token layout inference never uses
    # (42% of live tu93 steps had a span length absent from the whole corpus).
    # The reason this override existed still holds and is already in the base:
    # it breaks on `game._next_level`, so the last captured frame is this level's
    # clean solved board, not the next level's re-rolled palette. Verified
    # equivalent -- identical settled frame and solved/dead flags on the same
    # action stream across seeds 0-2.


if __name__ == "__main__":
    sys.exit(Tu93Solver.main())
