"""Mouse-click Lights Out (mc:lamelightsout).

A pointer-driven remake of the PuzzleScript game LameLightsOut
(data/puzzlescript_games/LameLightsOut.txt). Instead of walking a red cursor with
the arrow keys and pressing Action, you click a light directly with ACTION6.

Mechanic (identical to the original):
  * Every cell is a light that is either ON (white) or OFF (grey).
  * Clicking a cell toggles that cell **and its four orthogonal neighbours** --
    the classic "plus"-shaped Lights Out stamp.
  * A level is won when there are no OFF lights left (all white).

There is no cursor sprite -- the mouse IS the cursor -- so ACTION1-4 are unused and
only ACTION6 (click) is exposed. Each level's board size drives the camera (the
engine resizes the viewport to the level's ``grid_size``), so boards always fill
the frame regardless of shape.

Presentation: the board is displayed at a per-(seed, level) rotation (the shared
``AugmentedGame`` augmentation), and clicks are mapped back into game space, so the
same seed always renders at the same orientation for both recording and live play.

Solvability: every board here is guaranteed solvable. The fixed hand-authored set
was verified over GF(2); the per-seed randomised set is generated by scrambling the
all-ON solution with random clicks, and clicks are self-inverse, so replaying them
(in any order) solves the board.
"""

from __future__ import annotations

import random

from arcengine import (
    Camera,
    GameAction,
    Level,
    RenderableUserDisplay,
    Sprite,
)

from utils.arc_game import AugmentedGame

# ARC palette indices (see adapters/puzzlescript_adapter.py ARC_PALETTE_RGB).
ON_COLOR = 0          # white  -- original LightOn
OFF_COLOR = 2         # mid grey -- original LightOff
BACKGROUND_COLOR = 3  # dark grey -- original DarKGrey background (barely shows)
LETTERBOX_COLOR = 5   # black

# The camera is resized per level to the board's grid_size, so these are just the
# initial (largest) viewport; render output is always upscaled to 64x64.
CAM_W = 8
CAM_H = 8


class McLightsUI(RenderableUserDisplay):
    """Overlay: a brief click ripple + a top-row bar of remaining OFF lights."""

    CLICK_ANIM_FRAMES = 12

    def __init__(self, remaining: int, total: int) -> None:
        self._remaining = remaining
        self._total = total
        self._click_pos: tuple[int, int] | None = None
        self._click_frames = 0

    def update(self, remaining: int, total: int) -> None:
        self._remaining = remaining
        self._total = total

    def set_click(self, frame_x: int, frame_y: int) -> None:
        self._click_pos = (frame_x, frame_y)
        self._click_frames = McLightsUI.CLICK_ANIM_FRAMES

    def clear_click(self) -> None:
        """Drop any in-flight ripple. Called on every level change so a level's
        first frame is the clean board: the ripple otherwise outlives the click
        that solved the PREVIOUS level (it decays over renders, not actions) and
        would be drawn over the new board at a stale position -- making the first
        frames of a level depend on how the last one ended."""
        self._click_pos = None
        self._click_frames = 0

    @staticmethod
    def _plot_px(frame, h: int, w: int, px: int, py: int, color: int) -> None:
        if 0 <= px < w and 0 <= py < h:
            frame[py, px] = color

    @classmethod
    def _chebyshev_ring(cls, frame, h, w, cx, cy, r, color) -> None:
        if r <= 0:
            return
        for dy in range(-r, r + 1):
            for dx in range(-r, r + 1):
                if max(abs(dx), abs(dy)) == r:
                    cls._plot_px(frame, h, w, cx + dx, cy + dy, color)

    def render_interface(self, frame):
        import numpy as np

        if not isinstance(frame, np.ndarray):
            return frame
        h, w = frame.shape

        # Progress bar: one pip per light, lit (green) once that light is ON.
        lit = self._total - self._remaining
        for i in range(min(self._total, 20)):
            c = 14 if i < lit else 4
            self._plot_px(frame, h, w, 1 + i * 2, 1, c)

        # Click ripple.
        if self._click_pos and self._click_frames > 0:
            cx, cy = self._click_pos
            phase = McLightsUI.CLICK_ANIM_FRAMES - self._click_frames
            if phase < 6:
                ring_r = phase + 1 if phase < 3 else 6 - phase
                if ring_r > 0:
                    self._chebyshev_ring(frame, h, w, cx, cy, ring_r, 8)
            self._click_frames -= 1
        else:
            self._click_pos = None

        return frame


sprites = {
    "on": Sprite(
        pixels=[[ON_COLOR]],
        name="on",
        visible=True,
        collidable=False,
        tags=["light", "on"],
    ),
    "off": Sprite(
        pixels=[[OFF_COLOR]],
        name="off",
        visible=True,
        collidable=False,
        tags=["light", "off"],
    ),
}

# Toggle stamp: the clicked cell plus its four orthogonal neighbours.
_STAMP = [(0, 0), (1, 0), (-1, 0), (0, 1), (0, -1)]


def mk(layout: list[str], difficulty: int) -> Level:
    """Build a level from an on/off character grid ('1' = ON, '0' = OFF).

    Rows are strings of equal length; grid_size is (cols, rows).
    """
    rows = len(layout)
    cols = len(layout[0])
    assert all(len(r) == cols for r in layout), f"ragged layout: {layout}"
    sl: list[Sprite] = []
    for y, row in enumerate(layout):
        for x, ch in enumerate(row):
            key = "on" if ch == "1" else "off"
            sl.append(sprites[key].clone().set_position(x, y))
    return Level(
        sprites=sl,
        grid_size=(cols, rows),
        data={"difficulty": difficulty, "layout": [list(r) for r in layout]},
    )


# ---------------------------------------------------------------------------
# Fixed hand-authored levels (used when no seed is supplied). Every board is
# solvable over GF(2). The first four mirror the original PuzzleScript levels
# (with the red-cursor cell replaced by its plain light state).
# ---------------------------------------------------------------------------
_FIXED_LAYOUTS: list[list[str]] = [
    ["010"],                       # 1x3  (orig L1: O10)
    ["0101"],                      # 1x4  (orig L2: O101)
    ["10101"],                     # 1x5  (orig L3: i0101)
    ["00", "00"],                  # 2x2  (orig L4: o0/00)
    ["001", "011"],                # 2x3
    ["101", "010", "101"],         # 3x3 checkerboard
    ["000", "111", "000"],         # 3x3 lit band
    ["000", "000", "000"],         # 3x3 all off
]

levels = [mk(layout, i + 1) for i, layout in enumerate(_FIXED_LAYOUTS)]


# Per-seed randomised progression: (cols, rows). Board size grows with difficulty.
_SEED_SPECS = [(3, 1), (5, 1), (2, 2), (2, 3), (3, 3), (4, 3), (4, 4)]


def _apply_stamp(state: list[list[int]], x: int, y: int) -> None:
    rows, cols = len(state), len(state[0])
    for dx, dy in _STAMP:
        nx, ny = x + dx, y + dy
        if 0 <= nx < cols and 0 <= ny < rows:
            state[ny][nx] ^= 1


def _build_randomized_levels(rng: random.Random) -> list[Level]:
    """Scramble the all-ON solution with random clicks -> always solvable, never
    already solved."""
    out: list[Level] = []
    for i, (cols, rows) in enumerate(_SEED_SPECS):
        state = [[1] * cols for _ in range(rows)]  # start solved (all ON)
        cells = [(x, y) for y in range(rows) for x in range(cols)]
        n_clicks = max(1, (cols * rows) // 2)
        for x, y in rng.sample(cells, min(n_clicks, len(cells))):
            _apply_stamp(state, x, y)
        # Guarantee it isn't already solved (a scramble can cancel out).
        if all(v == 1 for row in state for v in row):
            _apply_stamp(state, *rng.choice(cells))
        layout = ["".join(str(v) for v in row) for row in state]
        out.append(mk(layout, i + 1))
    return out


class McLamelightsout(AugmentedGame):
    def __init__(self, seed: int | None = None) -> None:
        self._ui = McLightsUI(0, 1)
        self._rng = random.Random(seed)
        game_levels = (
            _build_randomized_levels(self._rng) if seed is not None else levels
        )
        # Per-(seed, level) display rotation. Must be prepared BEFORE the Camera
        # (the base turns the BOARD in set_level; the camera just renders it)
        self._init_augmentation(seed)
        super().__init__(
            "mc:lamelightsout",
            game_levels,
            Camera(
                0, 0, CAM_W, CAM_H,
                BACKGROUND_COLOR, LETTERBOX_COLOR,
                [self._ui],
            ),
            False,
            1,
            [6],
        )

    # --- board state -------------------------------------------------------
    def on_set_level(self, level: Level) -> None:
        cols, rows = self.current_level.grid_size
        self._cols, self._rows = cols, rows
        self._ui.clear_click()
        # Reference the (possibly cloned-on-reset) light sprites by position.
        self._cells: dict[tuple[int, int], Sprite] = {}
        for sp in self.current_level.get_sprites_by_tag("light"):
            self._cells[(sp.x, sp.y)] = sp
        self._sync_ui()

    def _is_on(self, x: int, y: int) -> bool:
        sp = self._cells.get((x, y))
        return bool(sp and "on" in sp.tags)

    def _set_cell(self, x: int, y: int, on: bool) -> None:
        old = self._cells.get((x, y))
        if old is not None:
            self.current_level.remove_sprite(old)
        key = "on" if on else "off"
        new = sprites[key].clone().set_position(x, y)
        self.current_level.add_sprite(new)
        self._cells[(x, y)] = new

    def _remaining_off(self) -> int:
        return sum(
            1 for (x, y) in self._cells if not self._is_on(x, y)
        )

    def _sync_ui(self) -> None:
        total = self._cols * self._rows
        self._ui.update(self._remaining_off(), max(1, total))

    def _grid_to_frame_pixel(self, gx: int, gy: int) -> tuple[int, int]:
        cam = self.camera
        cw, ch = cam.width, cam.height
        scale = min(int(64 / cw), int(64 / ch))
        x_pad = int((64 - (cw * scale)) / 2)
        y_pad = int((64 - (ch * scale)) / 2)
        return gx * scale + scale // 2 + x_pad, gy * scale + scale // 2 + y_pad

    # --- input -------------------------------------------------------------
    def step(self) -> None:
        if self.action.id != GameAction.ACTION6:
            self.complete_action()
            return

        # The frame is presented rotated, so a screen click has to be mapped back
        # into game space before the camera resolves it to a cell.
        x, y = self.screen_click_to_game(
            self.action.data.get("x", 0), self.action.data.get("y", 0))
        coords = self.camera.display_to_grid(x, y)
        if coords is None:
            self._ui.set_click(max(0, min(63, int(x))), max(0, min(63, int(y))))
            self.complete_action()
            return

        gx, gy = coords
        self._ui.set_click(*self._grid_to_frame_pixel(gx, gy))

        if not (0 <= gx < self._cols and 0 <= gy < self._rows):
            self.complete_action()
            return

        # Plus-shaped toggle centred on the clicked cell.
        for dx, dy in _STAMP:
            nx, ny = gx + dx, gy + dy
            if 0 <= nx < self._cols and 0 <= ny < self._rows:
                self._set_cell(nx, ny, not self._is_on(nx, ny))

        self._sync_ui()
        if self._remaining_off() == 0:
            self.next_level()

        self.complete_action()
